language: c

matrix:
  fast_finish: true
  include:
    - os: osx
      env CONFIG=debug

    - os: osx
      env CONFIG=release

install:
  - brew update
  - brew install ponyc pony-stable

script:
  - make test config=${CONFIG}
