version: 2
// TODO: also test on 32bit
jobs:
  vs-ponyc-release:
    docker:
      - image: ponylang/ponyc:release
    steps:
      - run: apt update
      - run: apt install -y make git
      - checkout
      - run: make test
  vs-ponyc-master:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - run: apt update
      - run: apt install -y make git
      - checkout
      - run: make test config=debug
      - run: make test config=release

workflows:
  version: 2
  commit:
    jobs:
      - vs-ponyc-release
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - vs-ponyc-master
